## Working with Arrays

Create a 3 x 6-dimensional array, containing only float values. 

In [10]:
import numpy as np

a = np.array([[1.5, 2, 3.5, 4, 5.5, 6], [7, 8.5, 9, 10.5, 11, 12.5], [13, 14, 15, 16, 17, 18]])

a

array([[ 1.5,  2. ,  3.5,  4. ,  5.5,  6. ],
       [ 7. ,  8.5,  9. , 10.5, 11. , 12.5],
       [13. , 14. , 15. , 16. , 17. , 18. ]])

Check the dimension you have created is correct (use “*.shape*”)

In [11]:
a.shape

(3, 6)

Substitute the 5th element from the 2nd row with 19.75.

In [12]:
a[1,4] = 19.75
a

array([[ 1.5 ,  2.  ,  3.5 ,  4.  ,  5.5 ,  6.  ],
       [ 7.  ,  8.5 ,  9.  , 10.5 , 19.75, 12.5 ],
       [13.  , 14.  , 15.  , 16.  , 17.  , 18.  ]])

Extract the 2nd and the 3rd row of the array you created. 

In [13]:
a[1]

array([ 7.  ,  8.5 ,  9.  , 10.5 , 19.75, 12.5 ])

In [14]:
a[2]

array([13., 14., 15., 16., 17., 18.])